### ISSUE TITLE
Crash when you upload the photo to the chat. (video attached)

### ISSUE THREAD

**Issue by Kravet** [GetStream/stream-chat-android#968] opened 2020-12-05 20:17 UTC
**Describe the bug**
App crashes when you upload the photo to the chat. See the video by the link below.
Note: uploading existing images, pdf, video works well.

**[Video how to reproduce](https://drive.google.com/file/d/1tJcUJs9MNAQhYwzsbWg-4u_wl2lERwD6/view?usp=sharing)**
**To Reproduce**
1. Go to the chat.
2. Choose make a picture.
3. take a picture from your phone
4. uploading..
5. crash

**SDK version**
- 4.4.6
- Android kotlin sdk

**Device:**
 - Oneplus 5t Android 10.
 - Samsung (forgot the model) Android 10.

**Comment by bychkovdmitry** [comment] 2020-12-07 08:23
@Kravet, thank you for reporting the issue. Unfortunately, we are not able to reproduce it. Could you share the crash stacktrace?

**Comment by Kravet** [comment] 2020-12-07 14:40
Hm, I can't reproduce it anymore, neither QA.. The issue just disappeared )

**Comment by JcMinarro** [comment] 2020-12-08 09:05
It seems related with #934 that has been already merged into the last version 
I am closing this issue as it is not reproducible anymore with the last version, 
Feel free to open a new issue if you get any unexpected behavior

**Closed by JcMinarro** 2020-12-08 09:05 UTC
Labels: bug
