### ISSUE TITLE
message's createdAt & createdLocallyAt

### ISSUE THREAD

**Issue by jisusushi** [GetStream/stream-chat-android#2725] opened 2021-12-01 06:10 UTC
**Describe the bug**
When I send a message in any channel, the message's `createdAt` and `createdLocallyAt` differ in about 3000ms. And the point is `createdAt` has **'earlier'** timeStamp.
This causes problem when using `chatDomain.markRead()`. It calls channelController's `markRead()` and it defines the last message's Date as the following rule; initially it checks the message's `createdAt` (which is null when initially sent) and then if it is null, it writes the value as the message's `createdLocallyAt`. So after the `markRead()` is called with lastMessageDate as `createdLocallyAt`, the `lastMarkReadEvent` can't be re-updated since the new `createdAt` is before `createdLocallyAt`(which is now the `lastMarkReadEvent`).
https://github.com/GetStream/stream-chat-android/blob/49b3bd7be8062e6052c6029c72535a98b057a973/stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/channel/ChannelController.kt#L225 
So the `lastReadDate` of `controller.read` is written as `createdLocallyAt` of the last message, and it causes problem in my app.

You can check the code in 'offline > channel > ChannelController > markRead (line 210~)'. 

**SDK version**
- 4.22.0

**To Reproduce**
In stream-chat-android sample app, 
1. check the `lastLoadedmessage`'s `createdAt`, `createdLocallyAt` and `controller.read.value?.lastReadDate` at 'Compose > viewModel > messages > MessageListViewModel > observeConversation' 's collect (line 217~)

**Expected behavior**
createdAt should be after the createdLocallyAt, or at least lastReadDate should refer to the createdAt, not createdLocallyAt.

**Device:**
 - Vendor and model: Samsung S21
 - Android version: 11

**Screenshots**

**Comment by samiuelson** [comment] 2021-12-02 12:20
Hi @jisusushi, thanks for reporting the issue. We will look into this and work on the fix.

**Comment by adasiewiczr** [comment] 2022-02-10 15:51
Hey @jisusushi,
we have released a new SDK version (4.28.2) that contains a fix for this issue.
Feel free to reopen this ticket if the issue is not solved.

**Closed by adasiewiczr** 2022-02-10 15:51 UTC
Labels: bug, next-release, core
