### ISSUE TITLE
Unreacting to a message is not removed from ownReactions after update

### ISSUE THREAD

**Issue by f4r33** [GetStream/stream-chat-android#3227] opened 2022-03-18 14:30 UTC
**Describe the bug**
If a user reacts to an already reacted (by someone else) message,  then unreacts, after the update in data, the counter is lowered but the reaction is still within ownReactions. The app uses custom UI components.

**SDK version**
- 4.30.1

**To Reproduce**
1. Go to a message with a reaction
2. React using the same reaction
3. Unreact the reaction
4. Counter is lowered but it is still inside "ownReactions"

**Expected behavior**
The reaction is removed from list of "ownReactions"

**Device:**
 - Vendor and model: Samsung S21+
 - Android version: 12

**Comment by amitkma** [comment] 2022-03-30 11:42
@f4r33 We tried to reproduce this problem but couldn't reproduce it. Could you please try the latest version 5.0.1? If you still see the error, please do share the source code of how you are deleting and observing the reactions. It would be very helpful.

**Comment by amitkma** [comment] 2022-04-04 15:25
@f4r33 Did you try the latest version?

**Comment by f4r33** [comment] 2022-04-05 12:08
Trying out the latest version right now. Having some issues with displaying the messages. As soon as I get it working I will test it out. Thanks.

**Comment by amitkma** [comment] 2022-04-22 15:23
Thanks for the information @f4r33. I am closing this issue but feel free to open it if you have more info or context to share.

**Closed by amitkma** 2022-04-22 15:23 UTC
Labels: bug, core
