### ISSUE TITLE
Issue with predicate filter

### ISSUE THREAD

**Issue by spvince** [GetStream/stream-chat-android#4243] opened 2022-10-05 15:15 UTC
**Describe the bug**

I use the code below to filter channel because i want to display in channel list view only channel which have 1 new message. If my app isn't started, then i receive a message, then i launch my app, it's work well. But when my app is launched and visible on screen, when i receive a new message the channel isn't displayed.

This code works well with sdk 4.30.1 but not with 5.8.1

```
              channelsListView.setChannelListItemPredicate { channelListItem ->
                    when (channelListItem) {
                        is ChannelListItem.LoadingMoreItem -> {
                            true
                        }
                        is ChannelListItem.ChannelItem -> {
                            val count = channelListItem.channel.getUnreadMessageCount(mSpUser.id)
                            Timber.d("initStreamChatView - predicate unread message in this channel : $count")
                            count > 0
                        }
                    }
                }
```

**SDK version**
- 5.8.1

**Device:**
 - Vendor and model: pixel 2 xl
 - Android version: 11

**Comment by bychkovdmitry** [comment] 2022-10-13 11:47
Hello @spvince 

Thank you for reporting this. Could you post the source code of `Channel::getUnreadMessageCount` method? Do you see your Timber log when a new message arrives? Does the `count` variable in your snippet change its value from 0 to 1 when a new message arrives?

```
Timber.d("initStreamChatView - predicate unread message in this channel : $count")
```

**Comment by spvince** [comment] 2022-10-13 13:04
Hi @bychkovdmitry 

Yes the count is equal to 1.

If i click on square device button 'Recent App Button',  app goes to background then i click on app, it came back to foreground. RecyclerView is refresh and channel is well displayed in list.

 
```
fun Channel.getUnreadMessageCount(userId: String): Int {
    var unreadMessageCount = 0
    val read: List<ChannelUserRead> = read

    if (read.isEmpty()) {
        return 0
    }

    val lastReadDate: Date = getReadDateOfChannelLastMessage(userId) ?: return 0

    val messages: List<Message> = messages
    for (i in messages.indices.reversed()) {
        val message = messages[i]
        if (message.user.id == userId || message.deletedAt != null) {
            continue
        }

        if ((message.createdAt?.time ?: 0) > lastReadDate.time) {
            unreadMessageCount++
        }
    }

    return unreadMessageCount
}
```

**Comment by MarinTolic** [comment] 2022-10-13 15:35
Hi @spvince,

We were able to confirm this bug.  However we don't have the definition of the `getReadDateOfChannelLastMessage()` you are using in your code, so we went with @bychkovdmitry's idea of using `channelListItem.channel.unreadCount` to get the unread count. If you intend to keep using your custom way of fetching the unread count, please send us all necessary function definitions so we can test our solution to the bug using your code as well in order to guarantee that it will work.

In the meantime, we will start working on a fix for this bug. :smile:

**Comment by spvince** [comment] 2022-10-13 15:43
Hi @MarinTolic 

Thanks for your return. I didn't seen this property `channelListItem.channel.unreadCount`. I will use it.

**Comment by MarinTolic** [comment] 2022-10-13 17:46
Hey @spvince,

Could you please check if this issue happens only with muted channels or with non-muted channels as well?
Thank you! :smile:

**Comment by spvince** [comment] 2022-10-14 07:38
Hi @MarinTolic,

Yes, this issue happens with muted and non-muted channels.

**Comment by MarinTolic** [comment] 2022-10-14 09:15
Hey @spvince ,

Could you please try the following code and apply these steps:

```kotlin
channelsListView.setChannelListItemPredicate { channelListItem ->
            when (channelListItem) {
                is ChannelListItem.LoadingMoreItem -> {
                    true
                }
                is ChannelListItem.ChannelItem -> {
                    val count = channelListItem.channel.unreadCount

                    (count ?: 0) > 0
                }
            }
        }
```

1. Uninstall you app from the phone/ emulator
2. Clean project and Invalidate Caches & Restart
3. Deploy a new build to your phone
4. Test the issue again and tell us if it repeats

Also, if the issue persists, please try to see if our newest release fixes the issue.
You can find the list of releases here: https://github.com/GetStream/stream-chat-android/releases

Sorry for the additional instructions, it seems to be a bit of a troublesome bug to reliably reproduce. :smile:
In our testing we were unable to reproduce it with non-muted channels.

**Comment by spvince** [comment] 2022-11-16 09:09
Hi @MarinTolic,

Any news ?

**Comment by MarinTolic** [comment] 2022-11-21 10:05
Hi @spvince,

We could not reproduce the issue you are facing.
It would be of great help to us if you could for instance reproduce the issue within a small app (something like our tutorials) and share it with us. 

Apologies for the tough time we are having in addressing this, it's difficult to solve this issue without being able to reproduce it first.

**Comment by spvince** [comment] 2022-11-21 13:49
Hi @MarinTolic ,

I understand. I made more research and I reproduce the issue that i have on your sample. For the moment I can't explain why i can see different behavior with your method predicate. The issue I've seen is due to UI not predicate.

Step to reproduce (with your sample) :
- Replace fragment_channels by the code below
- The list isn't displayed
- Click on "Mentions tab" then click on "Chats tab", the list is well displayed

```
<?xml version="1.0" encoding="utf-8"?>
<!--
    Copyright (c) 2014-2022 Stream.io Inc. All rights reserved.

    Licensed under the Stream License;
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

      https://github.com/GetStream/stream-chat-android/blob/main/LICENSE

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/stream_ui_white_snow"
    >

    <io.getstream.chat.android.ui.search.SearchInputView
        android:id="@+id/searchInputView"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_margin="8dp"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        />

    <androidx.core.widget.NestedScrollView
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:layout_marginTop="22dp"
        android:fillViewport="true"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/searchInputView"
        >

        <androidx.constraintlayout.widget.ConstraintLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            >

            <io.getstream.chat.android.ui.channel.list.ChannelListView
                android:id="@+id/channelsView"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_marginTop="8dp"
                app:layout_constrainedHeight="true"
                app:layout_constraintBottom_toTopOf="@+id/channels_empty_advice"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent"
                app:layout_constraintVertical_bias="0.0"
                app:streamUiChannelOptionsEnabled="true"
                app:streamUiLoadingView="@layout/channels_loading_view"
                />

            <TextView
                android:id="@+id/channels_empty_advice"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:textSize="18sp"
                android:text="Tu n’as pas d’autres messages"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                tools:text="Seuls les messages non-lus apparaissent ici."
                />

        </androidx.constraintlayout.widget.ConstraintLayout>
    </androidx.core.widget.NestedScrollView>

    <io.getstream.chat.android.ui.search.list.SearchResultListView
        android:id="@+id/searchResultListView"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:visibility="gone"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/searchInputView"
        />

</androidx.constraintlayout.widget.ConstraintLayout>
```

**Comment by filbabic** [comment] 2023-02-01 08:17
We've not had the ability to repro this at all and as such I'll close the issue since it's been a while.

**Closed by filbabic** 2023-02-01 08:17 UTC
Labels: bug
