### ISSUE TITLE
Deleted channels have null deletedAt field

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1557] opened 2021-03-16 05:51 UTC
When I delete a channel, I receive a `ChannelDeletedEvent`. This event has a `channel` object with valid `deletedAt` value. But, if I query this channel again, either from ChatClient or from Chat Domain, `deletedAt` value is still null.

I think either the API doesn't send us `deletedAt` field, or we aren't updating it in local-db.

**Comment by JcMinarro** [comment] 2021-03-16 12:27
Hello @rupinderjeet 

How are you querying it?
Which methods are you using for that?

I will need to check it with our backend team

**Comment by rupinderjeet** [comment] 2021-03-16 12:53
Hello @JcMinarro 

Here's all of them:

```
messageListViewModel.channel.observe(this) { channel ->
	val isDeleted = channel.deletedAt != null
}
```
```
val result = chatClient
	.channel(request.channelId)
	.query(QueryChannelRequest())
	.execute()

if (result.isSuccess) {
	val channel = result.data()
       val isDeleted = channel.deletedAt != null
}
```
```
val filter = Filters.and(
	Filters.eq("id", request.channelId), // not cid
	Filters.eq("type", request.channelType),
	Filters.`in`("members", listOf(targetUserId))
)

val querySort = QuerySort<Channel>().asc("last_message_at")
val queryChannelsRequest = QueryChannelsRequest(
	filter,
	request.offset,
	request.limit,
	querySort
)

val result = chatClient.queryChannels(queryChannelsRequest).execute()
if (result.isSuccess) {
	val channel = result.data().requireFirst()
        val isDeleted = channel.deletedAt != null
}
```

Also, I was checking logs from calls by `ChatClient`, I don't think backend is sending you `deletedAt` for these calls.

**Comment by JcMinarro** [comment] 2021-03-16 12:55
Hello @rupinderjeet 

I have been checking with our backend team and it is the expected behavior.
If you query for a channel, it uses a "get or create" implementation under the hood, so, in that case, because the channel is recreated the `deletedAt` property is null again.

Is it an issue for you?
Maybe you can talk to us about your use-case and we can help you how to solve it

**Comment by rupinderjeet** [comment] 2021-03-16 13:27
**Steps:**

1. User A, User B and User C are chatting in a channel.
2. User B disables the internet access. Locks the phone.
3. After some time, User A deletes the channel.
4. User B unlocks the phone. Enables the internet.
5. User B is seeing messages list now.

**Case: I don't check if channel exists in onResume()**
- User B sends message. 
			- If Internet is Enabled: Channel is truncated. Message is not sent because "Can't find channel with id messaging:SOME_CHANNEL_ID"
			- else Message is in progress to be sent. When internet is enabled, message is sent. All previous messages are visible. All new messages are being sent. Channel disappears if user calls `disconnect()` and `setUser()` again.

**Case: I check if channel exists in onResume(); Internet Enabled**
- Channel was deleted technically, but "querying this channel" resurrected it. Channel is truncated. Channel's name is lost. Channel has all members except User A. 
		- User B & User C continues chatting.
		- User A thinks channel is deleted for all.


In both cases, how do I tell the user that channel was deleted?

**Comment by rupinderjeet** [comment] 2021-03-22 07:37
Also, 

Suppose a moderator deleted the channel, but at the same time a user queried the channel, channel survives this deletion. So, if there is even a 2 second gap in channel-deletion and its removal from channel-list-ui, any user can just take over the channel and become its new owner.

**Comment by JcMinarro** [comment] 2021-03-31 16:06
Hello @rupinderjeet 
We have been investigating this case and because of the current implementation on the backend that I told you about some days ago, it is not possible.

Instead of delete it, maybe you can achieve the same behavior by adding some extra field to the `extraData` map and doing some logic in your side.
Filters allow you to check custom fields as well. So you could add some custom field to your channel:
```
channel.extraData["customDeletedField"] = true
```

Then, when you want to filter those channel, use the following filter:
```
Filters.neq("customDeletedField", true)
```

On the `Channel::extraData` map you can add the info you want, it accepts any primitive type

**Comment by JcMinarro** [comment] 2021-03-31 17:06
Yep, `extraData` is clear when you delete the channel, but I am not suggesting you to delete it, but only update with this property.
Then, in your side, you can add some logic to know if you are able to use this channel or not.
BTW, With the filter I showed previously, it shouldn't arrive when you query for channels

**Comment by rupinderjeet** [comment] 2021-03-31 17:14
Yes, thank you. I understood it later. I will try this, and give you a feedback if this works for me.

**Comment by zsmb13** [comment] 2021-04-06 11:25
@rupinderjeet Is this issue still relevant, or can we close it?

**Comment by rupinderjeet** [comment] 2021-04-06 11:35
We are experimenting with offered suggestion in iOS and Web platforms. For Android, it seems to be working as of now. If there's any issue regarding this, I will open one again.

But, I wish you guys could give me one API to get channel information without recreating it if it was deleted. 💔

**Closed** 2021-04-06 13:41 UTC
