### ISSUE TITLE
NotEquals filter does not work for channels with empty extraData

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1677] opened 2021-04-05 08:09 UTC
When I use a custom `extraData` key in a filter to receive channels, channels with empty `extraData` are not returned.

Here's my code:
```
val filter = Filters.and(
	Filters.eq("id", request.id),
	Filters.eq("type", request.type),
	Filters.ne("customField", true),
	Filters.`in`("members", listOf(targetUserId))
)

val querySort = ...
val queryChannelsRequest = QueryChannelsRequest(filter, offset = 0, limit = 1,  querySort)
```

The key `customField` doesn't exist in the channel I am querying and `channel.extraData` is empty. If I remove the `customField` filter, I receive the channel instance.

Using `ne` filter was suggested in https://github.com/GetStream/stream-chat-android/issues/1557#issuecomment-811185630. I am under the impression that with this filter I can query the channels where the `customField` doesn't even exist. If this isn't the case, is there a filter that I can use to check if a custom key is present in `extraData`?

**Comment by JcMinarro** [comment] 2021-04-05 12:17
Hello @rupinderjeet 
It seems to be a bug in our side when the filter is applied. We are investigating it.
BTW, There is a filter that check if a custom field is present or not, This filter is `Filters.exists()`

**Comment by JcMinarro** [comment] 2021-04-05 12:58
Hello @rupinderjeet 
We have been doing some tests in our side and the `Filters.ne()` filter works fine.
It is used internally into our default filter for `ChannelsViewModel` as you can check out [here](https://github.com/GetStream/stream-chat-android/blob/main/stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/viewmodel/ChannelListViewModel.kt#L33).
You can add your own filter there and verify on the the [sample-app](https://github.com/GetStream/stream-chat-android/tree/main/stream-chat-android-ui-components-sample) that it is working fine

**Comment by rupinderjeet** [comment] 2021-04-05 13:01
Ok @JcMinarro I will check again, thanks

**Comment by adasiewiczr** [comment] 2021-04-07 07:55
Hey @rupinderjeet, is this issue still relevant, or can we close it?

**Comment by rupinderjeet** [comment] 2021-04-07 08:14
Hello @adasiewiczr 

Please allow me sometime. I will give you feedback in about 4 hours.

**Comment by rupinderjeet** [comment] 2021-04-07 13:53
Hello @adasiewiczr & @JcMinarro 

Please try with this gist: https://gist.github.com/rupinderjeet/505b3b1857ef048cb0fb66cf89e02bec

Make sure to call the function on a background thread.

I hope I am not doing something wrong.

**Comment by adasiewiczr** [comment] 2021-04-08 12:29
Hey @rupinderjeet,
thanks for the gist, it was really helpful.
I've been able to reproduce this behavior and we are going to investigate it.
As a workaround I would recommend to replace `Filters.ne("will-this-work", true),` with `Filters.or(Filters.notExists("will-this-work"), Filters.ne("will-this-work", true))`.

**Comment by adasiewiczr** [comment] 2021-04-15 12:04
Hey @rupinderjeet,
I just want to confirm the solution works in your case.

**Comment by rupinderjeet** [comment] 2021-04-15 12:37
Hello @adasiewiczr 

I do not have this filter in code for now. Since I was querying only for one channel, I thought it may be better to just check the result contents when I receive them. i.e. verify `extraData` properties on my end.

About the filter you shared with me, I haven't tested it yet, and forgot about it, but I intend to test it once now in my free time. I believe this will work.

About the issue with `ne` filter, I think it is reasonable to consider that a not-equals filter checks only equality, and not existence. But, I, also, think that commonly people will assume otherwise since it doesn't suggest strictness of its name. 

If you guys aren't working/supporting it, feel free to close this issue. If I encounter any issue, I will report as new. 

Thank you.

**Comment by adasiewiczr** [comment] 2021-04-15 13:50
It is going to be fixed but for now, in such cases, we recommend combining `notExists` and `ne` filters.

**Closed by adasiewiczr** 2021-04-15 13:50 UTC
Labels: bug
