### ISSUE TITLE
App Crash After click on Attach in Chat (Java Android)

### ISSUE THREAD

**Issue by dheerajsinghrathore** [GetStream/stream-chat-android#3691] opened 2022-06-17 05:04 UTC
**Describe the bug**
App is crashing after implement the demo code as per your doc. I want to test in my application in java programming language but when I am clicking on Attach option the app is crashing.

**SDK version**
- 31

**To Reproduce**
1. Go to Chat Screen
2. Click on attach icon
3. App crash

android.view.InflateException: Binary XML file line #47 in (app_package_name):layout/design_bottom_sheet_dialog: Could not inflate Behavior subclass com.google.android.material.bottomsheet.BottomSheetBehavior
Caused by: java.lang.RuntimeException: Could not inflate Behavior subclass com.google.android.material.bottomsheet.BottomSheetBehavior
at androidx.coordinatorlayout.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:649)
at androidx.coordinatorlayout.widget.CoordinatorLayout$LayoutParams.<init>(CoordinatorLayout.java:2896)
at androidx.coordinatorlayout.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:1740)
at androidx.coordinatorlayout.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:112)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)

**Comment by TGazica** [comment] 2022-06-21 10:26
Hey @dheerajsinghrathore,

Thanks for letting us know about the issue. We will check it out and get back to you with more information as soon as possible.

**Comment by adasiewiczr** [comment] 2022-07-05 08:34
hey @dheerajsinghrathore,
could you give us more information about the issue and configuration?
- Which Stream SDK version are you using?
- Are you using standalone components (for example `MessageInputView`) or Activities/Fragments?
- Are you using Material Theme for your application?

**Comment by dheerajsinghrathore** [comment] 2022-07-13 03:23
Which Stream SDK version are you using?
**implementation "io.getstream:stream-chat-android-ui-components:5.4.0"**

Are you using standalone components (for example MessageInputView) or Activities/Fragments?
**I am using in Activity**

Are you using Material Theme for your application?
I am Using Material Design or Theme

**Comment by adasiewiczr** [comment] 2022-07-13 07:45
hey @dheerajsinghrathore,
we were trying to reproduce this crash without luck.
Could you provide us with a minimal project in which the crash is reproducible?

**Comment by dheerajsinghrathore** [comment] 2022-07-14 04:22
Hi @adasiewiczr  
I am trying in demo project. I am using Activity in entire project, not navigation component.

You can also try with activity only then App will crash After click on Attach option.

**Comment by bychkovdmitry** [comment] 2022-08-31 13:20
Hello @dheerajsinghrathore 

Are you still struggling with this issue? Could you tell us, which theme are you using for your application and activity? Ideally if you could send us the code snippets with your themes. Thanks

Also, a similar issue here:
https://github.com/GetStream/stream-chat-android/issues/2419#issuecomment-932119469

**Comment by filbabic** [comment] 2022-09-12 06:53
Closing this one due to inability of repro.

**Closed by filbabic** 2022-09-12 06:53 UTC
Labels: bug
