### ISSUE TITLE
My themes aren't working in latest SDK releases

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#2301] opened 2021-09-02 10:21 UTC
Up until now, we have been using streamchat-sdk v4.11.0. But, after upgrading stream-chat sdk to latest available, my theme colors are no longer working for custom views in SDK. I followed all of release notes, but I am unable to get them working. Maybe I missed something. 

Here's how I do it:

#### values/styles.xml
    <style name="ChatSdkTheme" parent="Theme.MaterialComponents">
        <item name="colorAccent">#FF0000</item>
        <item name="colorSecondary">#FF0000</item>
    </style>

#### AndroidManifest.xml
    <activity
        android:name=".channel.list.ChannelsActivity"
        android:screenOrientation="portrait"
        android:theme="@style/ChatSdkTheme" />

#### layout/channels_activity.xml [example]
    <androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="?colorAccent">
	
            <io.getstream.chat.android.ui.channel.list.ChannelListView
                android:id="@+id/channel_list_view"
                android:layout_width="0dp"
                android:layout_height="0dp"
                android:background="?colorAccent"
                android:layout_marginVertical="@dimen/_64sdp"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent" />

    </androidx.constraintlayout.widget.ConstraintLayout>

This is what I see in layout-editor and device screen:

<img src="https://user-images.githubusercontent.com/14011726/131826318-6cc954cb-b6fd-4a4b-af4d-96acb55cb186.png" alt="Screenshot 2021-09-02 at 3 42 36 PM" width="300" height="300" />

Why is `ChannelListView`'s `colorAccent` different? If I were to declare a custom-attrib (say `colorAccentWhatever`), it works.

I have, also, checked [Theming Guide](https://getstream.io/chat/docs/sdk/android/ui/theming/). The `TransformStyle` theming works, but it is hard to maintain for me as of now.

Following doesn't work for me at all. I am working on trying to use it at the moment.
```<item name="streamUiTheme">@style/StreamTheme</item>```

**Describe the bug**
Written Above.
**SDK version**
- 4.11.0+ to 4.17.2

**To Reproduce**
1. Written Above

**Expected behavior**
My declared theme attributes are used to show the UI

**Device:**
 - Vendor and model: All
 - Android version: 10

**Screenshots**
Attached Above.

**Comment by rupinderjeet** [comment] 2021-09-02 10:42
Here's how I tried new theming guidelines:

#### values/styles.xml
    <style name="ChatSdkTheme" parent="Theme.MaterialComponents">
        <item name="colorAccent">#FF0000</item>
        <item name="streamUiTheme">@style/ChatSdkTheme.StreamChat</item>
    </style>
    
#### values/stream_themes.xml
    <style name="ChatSdkTheme.StreamChat" parent="@style/StreamUiTheme">
        <item name="streamUiChannelListViewStyle">@style/ChatSdkTheme.ChannelListViewStyle</item>
    </style>

    <style name="ChatSdkTheme.ChannelListViewStyle" parent="StreamUi.ChannelListView">
        <item name="streamUiUnreadMessageCounterBackgroundColor">?colorAccent</item>
        <item name="streamUiChannelsItemSeparatorDrawable">@drawable/channels_separator</item>
    </style>


Both of these values aren't updated in the UI. Here's an example:
![Screenshot 2021-09-02 at 4 12 18 PM](https://user-images.githubusercontent.com/14011726/131830073-dfe40550-cdf6-4525-96cd-73e5ea9615e2.png)

**Comment by rupinderjeet** [comment] 2021-09-02 11:04
Everything works if I use following:
1) Direct color declarations: @color/blue or "#0000FF"
2) Custom attributes e.g. `betterColorAccent` instead of `colorAccent`, `betterColorPrimary` instead of `colorPrimary`

**Comment by rupinderjeet** [comment] 2021-09-02 11:27
My attribute declarations work only if I add `streamUiValidTheme` with `true` value. But, now, I think I need to add all of the styles because it crashes otherwise with following exception. Is there definition to what constitutes a valid theme in this context?

```
android.view.InflateException: Binary XML file line #15 in test.scu4172:layout/stream_ui_channel_list_item_view: Binary XML file line #20: You must supply a layout_width attribute.
```

![Screenshot 2021-09-02 at 4 52 45 PM](https://user-images.githubusercontent.com/14011726/131835262-14d4320f-a95c-499d-88ac-5f805938259b.png)

This feels like cheating!

**Comment by amitkma** [comment] 2021-09-02 11:32
It is happening probably because our components are wrapped in StreamTheme which has a default material accent color (light green). Ideally, it should respect the user theme attributes.

**Comment by rupinderjeet** [comment] 2021-09-02 13:29
Hello @amitkma 

> it should respect the user theme attributes
You are referring to android-attributes (like `colorAccent`) as "user theme attributes", right?

Please let me know if I am following the theming-guide wrong. How can I tell these UI components to use my styles instead?

**Comment by amitkma** [comment] 2021-09-02 13:37
Yes, I am referring to android theme attributes like colorAccent, colorPrimary etc. 

You are using them correctly but it won't work because these components are wrapped with StreamUiTheme which has a different parent (not the app theme). So it can't access the theme attributes set in the app theme.

**Comment by adasiewiczr** [comment] 2021-09-13 09:49
Hey @rupinderjeet,
you don't need to provide all the styles - you can use our `Theme` as a parent and all necessary attributes should be already there. You can find an example in our sample app [here](https://github.com/GetStream/stream-chat-android/blob/main/stream-chat-android-ui-components-sample/src/main/res/values/themes.xml#L2).
Another thing - you don't need to set a theme to each component like this: ` android:theme="@style/ChatSdkTheme.Channels"`. The only thing you need to do is to override one of the available style attributes inside `ChatSdkTheme.StreamChat`. The list of available styles is available [here](https://github.com/GetStream/stream-chat-android/blob/main/stream-chat-android-ui-components/src/main/res/values/attrs.xml#L7).
In order to customize components you can use:
- Attributes
- Themes
- StyleTransformer
You can find more detailed docs [here](https://getstream.io/chat/docs/sdk/android/ui/theming/#theming).
Let me know if you have any further questions

**Comment by rupinderjeet** [comment] 2021-09-13 12:19
Hello @adasiewiczr 

Using parent themes, I am unable to change `colorAccent` defined by your themes. Is this intentional?

As of now, I had to create my own `attr` because I can't modify `colorAccent` and other related `attr`s..
```
<attr name="colorStreamChatPrimary" format="color" />
<attr name="colorStreamChatPrimaryDark" format="color" />
<attr name="colorStreamChatOnPrimary" format="color" />
<attr name="colorStreamChatAccent" format="color" />
<attr name="colorStreamChatBackground" format="color" />
<attr name="colorStreamChatOnBackground" format="color" />
<attr name="colorStreamChatSurface" format="color" />
<attr name="colorStreamChatOnSurface" format="color" />
<attr name="colorStreamChatControlHighlight" format="color" />
```

**Comment by adasiewiczr** [comment] 2021-09-22 11:48
Hey @rupinderjeet,
that's the expected behavior. We don't allow to override colors via `theme`. 
Instead, you can override our [colors.xml](https://github.com/GetStream/stream-chat-android/blob/main/stream-chat-android-ui-components/src/main/res/values/colors.xml) or use component's attributes to override color or drawable.
All attributes are grouped into `attr` files with the component's name as a prefix. For example: [here](https://github.com/GetStream/stream-chat-android/blob/main/stream-chat-android-ui-components/src/main/res/values/attrs_channel_list_view.xml#L19) you can find attributes for `ChannelListView` component.
I'm closing this issue but let me know if you have any further questions.

**Closed by adasiewiczr** 2021-09-22 11:48 UTC
Labels: bug
