### ISSUE TITLE
Response of `ChatDomain.threadLoadMore` does not return `quote_message`

### ISSUE THREAD

**Issue by jisusushi** [GetStream/stream-chat-android#2256] opened 2021-08-20 09:20 UTC
**Describe the bug**
When `ChatDomain.loadOlderMessages` is called, the SDK use this api `https://chat.stream-io-api.com/channels/{channel_type}/{id}/query`. And it returns `quote_message` properly. However, when `ChatDomain.threadLoadMore` is called, the SDK use api of `https://chat.stream-io-api.com/messages/{messageId}/replies`. This returns `quote_message_id` but `quote_message` is omitted. 

**SDK version**
- 4.16.0

**Expected behavior**
`ChatDomain.threadLoadMore` should return the `quote_message`

**Screenshots**

![image (1)](https://user-images.githubusercontent.com/52556621/130211473-08ffe900-7699-4457-b45a-129093b9b1e0.png)

**Comment by bychkovdmitry** [comment] 2021-08-23 09:01
Hello @jisusushi 
Thanks for reaching out. We'll take a look into this as soon as we can.

**Comment by bychkovdmitry** [comment] 2021-08-23 18:51
Thanks you again for reporting this. Our backend team is already working on the fix.

**Comment by bychkovdmitry** [comment] 2021-08-24 12:45
@jisusushi The issue was fixed on the backend side and is being rolled out. The process can potentially take a week or two. Let us know if the issue is critical for you and we will try to speed up the process.

**Comment by jisusushi** [comment] 2021-08-25 01:50
First of all, thanks for fixing this quickly. But it would be much better if you guys can speed it up. We're quoting the parent message automatically when writing inside thread, and at this point the bug is bothering us. When we're switching around main chatroom and thread screen repeatedly, the parent message does not appear properly. This is kind of serious bug for us, so I wish it to be fixed asap :)

**Comment by ogkuzmin** [comment] 2021-09-08 09:01
@jisusushi 
Did you have a chance to check the issue in the recent version of SDK?

**Comment by adasiewiczr** [comment] 2021-09-13 09:41
Hello @jisusushi 
Closing the issue for now. Feel free to reopen if you are still experiencing the issue.

**Closed by adasiewiczr** 2021-09-13 09:41 UTC
Labels: bug
