### ISSUE TITLE
Back button on message list doesn't navigate back initially

### ISSUE THREAD

**Issue by zsmb13** [GetStream/stream-chat-android#2363] opened 2021-09-17 14:56 UTC
**Describe the bug**

You have to tap the hardware back button more than once to go back from MessagesActivity to ChannelActivity in the Compose sample app.

**To Reproduce**

1. Open a channel
2. Tap in the message input view (opens keyboard)
3. Tap back (closes keyboard)
4. Tap back (does nothing ⚠)
5. Tap back (navigates back correctly)

**Expected behavior**
Back navigation in step 4 above

**Device:**
 - Any

**Comment by laksh-21** [comment] 2021-09-24 18:15
This happens because in Compose, on the first back press, the keyboard closes and on the second one the TextField loses focus so in step 4, the TF is losing focus instead of doing nothing.
I think this can be fixed with a back press handler. Can I work on this?

**Comment by filbabic** [comment] 2021-09-25 09:16
Hey @laksh-21!

Thank you so much for reaching out! Yeah I think that's what's going on, so if you want to work on this to help out, that would be amazing! :]

**Comment by laksh-21** [comment] 2021-09-25 10:37
Sure @filbabic I'd love to work on this. :)

**Comment by filbabic** [comment] 2021-09-27 08:37
Hey @laksh-21!

Thank for the help! Could you reach out to me via Slack (e.g. on the Kotlin workspace) or via email (filip.babic@getstream.io)? :]

Just so that we can chat in case you need to jump in on a call or something or want to ask me any questions around this?

Thanks!

**Comment by filbabic** [comment] 2021-09-30 07:47
This is blocked until the new version of compose comes out, as the issue is fixed there.

For more reference: https://issuetracker.google.com/issues/192433071.

Thank you so much @laksh-21 for helping out with this!

**Comment by bychkovdmitry** [comment] 2022-02-23 13:09
No longer reproducible after Compose was updated to 1.1.0.

**Closed** 2022-02-23 13:09 UTC
Labels: bug, compose
