### ISSUE TITLE
[4.7.0] Not able to see custom channels

### ISSUE THREAD

**Issue by iosiappmemes** [GetStream/stream-chat-android#1585] opened 2021-03-19 05:31 UTC
Our backend has created some custom channels that have ID format like this:
```
global:muc-random-hex-string
```

In v4.6.0, I was able to fetch these custom channels with this filter:
```
Filters.eq("type", "global")
```

But, in v4.7.0, I am not able to fetch these channels with same filter. Instead, empty-channels message appears in `ChannelsView`.

When I upgraded stream dependency to v4.7.0, I followed migration guide from release page. i.e. corrected package for `FilterObject`.

**Comment by JcMinarro** [comment] 2021-03-19 11:13
Hello @iosiappmemes 

Could you show us how you are adding this filter?

**Comment by rupinderjeet** [comment] 2021-03-19 11:38
Hello @JcMinarro 

It was me, I accidentally created the issue from another system.

Here's how I initiate the `ChannelsViewModel`
```
val channelsViewModel = ChannelsViewModelFactory(
	createFilter(currentUser),
	ChannelsViewModel.DEFAULT_SORT
).create(ChannelsViewModel::class.java)
```

Here's the `createFilter()` function
```
/* override */ fun createFilter(currentUser: User): FilterObject {
	return Filters.eq("type", "global")
}
```

**Comment by bychkovdmitry** [comment] 2021-03-23 06:31
Hello @rupinderjeet

Is your user the member of this "global" channel? If yes, could you try the following filter:
```
Filters.and(Filters.eq("type", "messaging"), Filters.`in`("members", listOf(currentUser.id)))
```

**Comment by rupinderjeet** [comment] 2021-03-23 06:41
Hello @bychkovdmitry 

These channels are created by backend with a custom channel-type as I mentioned.

So, channel `type` is not `messaging`. It is `global`.

And, I am not a member of this chat. As our backend has told me, I do not need to be a member of this chat to send a message. So, some kind of channel settings on backend's part allows me to access the channel, send messages without actually joining the channel. There's no member list either. I get empty members even when there are 7 people typing.

These custom channel-types are working for me in `4.6.0`, not in `4.7.0`.

**Comment by bychkovdmitry** [comment] 2021-03-23 07:21
Sorry @rupinderjeet , I intended to write:
```
Filters.and(Filters.eq("type", "global"), Filters.`in`("members", listOf(currentUser.id)))
```

Thanks, now the issue is clear to us. We are working on the solution.

**Comment by adasiewiczr** [comment] 2021-03-24 13:44
Hey @iosiappmemes, thanks for reporting this issue. It has been fixed in the PR mentioned above and will be shipped in the next release.

**Closed** 2021-03-31 17:40 UTC
Labels: next-release
