### ISSUE TITLE
Crash in MessageInputView

### ISSUE THREAD

**Issue by spvince** [GetStream/stream-chat-android#2063] opened 2021-07-16 14:37 UTC
**Describe the bug**
I have a crash when i open my chat view.

**My code**
```
   <io.getstream.chat.android.ui.message.input.MessageInputView
            android:id="@+id/chat_message_input_view"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:background="@color/white"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent" />
```

**Crash**
```

Caused by: android.view.InflateException: Binary XML file line #11 in :layout/stream_ui_message_reply_view: Binary XML file line #11: You must supply a layout_width attribute.
     Caused by: java.lang.UnsupportedOperationException: Binary XML file line #11: You must supply a layout_width attribute.
        at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:830)
        at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:8231)
        at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:8429)
        at androidx.constraintlayout.widget.ConstraintLayout$LayoutParams.<init>(ConstraintLayout.java:2691)
        at androidx.constraintlayout.widget.ConstraintLayout.generateLayoutParams(ConstraintLayout.java:1916)
        at androidx.constraintlayout.widget.ConstraintLayout.generateLayoutParams(ConstraintLayout.java:482)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.kt:57)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.kt:48)
        at io.getstream.chat.android.ui.databinding.StreamUiMessageReplyViewBinding.inflate(StreamUiMessageReplyViewBinding.java:74)
        at io.getstream.chat.android.ui.message.list.adapter.view.internal.MessageReplyView.<init>(MessageReplyView.kt:32)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:852)
        at android.view.LayoutInflater.createView(LayoutInflater.java:774)
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.createCustomViewInternal(-ViewPumpLayoutInflater.kt:209)
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.access$createCustomViewInternal(-ViewPumpLayoutInflater.kt:19)
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater$PrivateWrapperFactory2ViewCreator.onCreateView(-ViewPumpLayoutInflater.kt:421)
        at com.lokalise.sdk.LokalisePreInterceptor.inflateView(LokaliseInterceptor.kt:144)
        at com.lokalise.sdk.LokalisePreInterceptor.intercept(LokaliseInterceptor.kt:71)
        at io.github.inflationx.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.kt:30)
        at com.lokalise.sdk.LokalisePostInterceptor.intercept(LokaliseInterceptor.kt:50)
        at io.github.inflationx.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.kt:30)
        at io.github.inflationx.viewpump.ViewPump.inflate(ViewPump.kt:36)
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater$PrivateWrapperFactory2.onCreateView(-ViewPumpLayoutInflater.kt:399)
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:237)
```

**SDK version**
- 4.14.1
i didn't have the crash in version 4.13.0

**To Reproduce**
1. open a chat view

**Expected behavior**
No crash

**Device:**
 - Vendor and model: google pixel 2
 - Android version: 11

**Comment by samiuelson** [comment] 2021-07-16 20:01
The issue is already fixed on `develop` branch. The release will be available next week.

**Comment by adasiewiczr** [comment] 2021-07-19 12:38
Hey @spvince,
We've released a new version with the fix mentioned above. You can check it [here](https://github.com/GetStream/stream-chat-android/releases/tag/4.14.2).

**Closed by adasiewiczr** 2021-07-19 12:38 UTC
Labels: bug, next-release
