### ISSUE TITLE
Missing memberCount

### ISSUE THREAD

**Issue by grabos** [GetStream/stream-chat-android#1824] opened 2021-04-30 09:24 UTC
https://github.com/GetStream/stream-chat-android/blob/d2dd0dab7ca52ed91332922a563994dd755069c8/stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChannelData.kt#L69

Someone forgot about assigne `memberCount` in this place. Now `memberCount` is always `0` in ViewModel

**Comment by zsmb13** [comment] 2021-04-30 09:27
Looks like a duplicate of https://github.com/GetStream/stream-chat-android/issues/1778

Please check 4.9.1 where we fixed this.

**Comment by zsmb13** [comment] 2021-05-11 07:09
Will close this as it's already fixed and also inactive. Let me know if you have any remaining issues on the latest version.

**Closed by zsmb13** 2021-05-11 07:09 UTC
