### ISSUE TITLE
Crash onbackpressed

### ISSUE THREAD

**Issue by spvince** [GetStream/stream-chat-android#2655] opened 2021-11-22 08:59 UTC
**Describe the bug**
Crash in my firebase crashlytics.

**SDK version**
- 4.22.0

**CRASH**
```
Fatal Exception: java.lang.IllegalStateException: FragmentManager is already executing transactions
       at android.app.FragmentManagerImpl.ensureExecReady(FragmentManager.java:2004)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2060)
       at android.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:870)
       at android.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:831)
       at android.app.Activity.onBackPressed(Activity.java:3197)
       at androidx.activity.ComponentActivity.access$001(ComponentActivity.java:100)
       at androidx.activity.ComponentActivity$1.run(ComponentActivity.java:137)
       at androidx.activity.OnBackPressedDispatcher.onBackPressed(OnBackPressedDispatcher.java:197)
       at androidx.activity.ComponentActivity.onBackPressed(ComponentActivity.java:592)
       at io.getstream.chat.android.ui.gallery.AttachmentGalleryActivity.setupGallery(AttachmentGalleryActivity.kt:86)
       at io.getstream.chat.android.ui.gallery.AttachmentGalleryActivity.$r8$lambda$7U9g3fgJ8miwR4qULomsmTQbiPQ()
       at io.getstream.chat.android.ui.gallery.AttachmentGalleryActivity$$ExternalSyntheticLambda4.onChanged(:4)
       at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
       at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:146)
       at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:468)
       at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:425)
       at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
       at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
       at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
       at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
       at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
       at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
       at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:144)
       at androidx.lifecycle.ReportFragment.onStart(ReportFragment.java:109)
       at android.app.Fragment.performStart(Fragment.java:2548)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1334)
       at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1576)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1637)
       at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3050)
       at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3007)
       at android.app.FragmentController.dispatchStart(FragmentController.java:194)
       at android.app.Activity.performStart(Activity.java:7356)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3145)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7078)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

**Device:**
 - Vendor and model: Samsung Galaxy A8
 - Android version: 9

**Comment by ogkuzmin** [comment] 2021-11-22 17:41
Hello, @spvince
Thanks for submitting the issue!
I tried to reproduce it and couldn't.  Can you specify more details? How many users are affected by this? Does it happen only with specific devices/android versions? 
Additionally, I see `AttachmentGalleryActivity`  do back press on `setupGallery` if empty attachments list is trying to be shown. It's weird scenario. SO any additional info can help us

**Comment by spvince** [comment] 2021-11-23 09:06
Hi @ogkuzmin ,
For the moment i have only one user with Samsung Galaxy A8 phone with android 9. He has reproduce crash 2 times. If i have additional information i will give you but i don't understand the scénario.

**Comment by adasiewiczr** [comment] 2021-12-10 08:47
hey @spvince,
did you manage to get more information about this crash?

**Comment by spvince** [comment] 2021-12-14 17:26
Hi @adasiewiczr ,
For the moment, no.

**Comment by adasiewiczr** [comment] 2021-12-21 12:00
Hey @spvince,
we were unable to reproduce this issue and I'm going to close this issue for now.
Feel free to reopen it if you will receive more reports or have additional information.

**Closed by adasiewiczr** 2021-12-21 12:00 UTC
Labels: bug
