### ISSUE TITLE
[4.8.0] AttachmentGalleryActivity crashes when bottom-right icon is tapped

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1661] opened 2021-04-01 11:40 UTC
Edit:

This issue is with theme. Popup Menu from top-right icon has same background and foreground color. Bottom-right icon tries to open a BottomSheet which fails due to some missing attribute from theme.

**Comment by rupinderjeet** [comment] 2021-04-01 11:45
Declaring activity in manifest and assigning app's theme fixes the issue.

```
<activity
	android:name="io.getstream.chat.android.ui.gallery.AttachmentGalleryActivity"
	android:configChanges="uiMode"
	android:theme="@style/Theme.ChatApp" />
```

**Comment by rupinderjeet** [comment] 2021-04-01 11:58
Also, in dark-mode, when image is tapped on this activity, background becomes white.

**Comment by leandroBorgesFerreira** [comment] 2021-04-01 13:51
Hi @rupinderjeet. We are going to take a in this problem and push a fix asap.

About the dark-mode style in the `AttachmentGallery`, this is the intended behaviour. It becomes black in the light-mode and white in the dark-mode so the picture is put in evidence. Do you think this is something that doesn't make sense for your design?

**Comment by rupinderjeet** [comment] 2021-04-01 14:32
Hi @leandroBorgesFerreira 

Thank you.

About the dark-theme, sudden color shift is a mild annoyance when the image is mostly horizontal i.e. 2:1.

I just want to reduce digital eye strain, it will be great if you can help me opt-out of this.

**Comment by leandroBorgesFerreira** [comment] 2021-04-01 17:44
I believe this is not configurable at the moment. Let us add a field to configure this.

**Comment by leandroBorgesFerreira** [comment] 2021-04-01 17:46
About the crash you described, could you provide us the stacktrace?

**Comment by rupinderjeet** [comment] 2021-04-01 18:54
Sure, I will add it here tomorrow.

**Comment by rupinderjeet** [comment] 2021-04-05 04:59
Hello @leandroBorgesFerreira 

here's the [crash log](https://github.com/GetStream/stream-chat-android/files/6256409/log1661.txt)

**Comment by leandroBorgesFerreira** [comment] 2021-04-05 19:36
@rupinderjeet  Which theme are you using in your app?

**Comment by rupinderjeet** [comment] 2021-04-06 07:45
Hello @leandroBorgesFerreira 

My project's application tag is using an AppCompat theme by default, which I am not able to change due to some work by other developers. 

I am accessing stream-sdk in different module inside project. In all activities related to chat, I am using material-components theme.

As I mentioned in the issue description, issue was indeed because of this scenario I think.

**Comment by zsmb13** [comment] 2021-04-06 07:54
Could you adopt a [Bridge Theme](https://github.com/material-components/material-components-android/blob/master/docs/getting-started.md#bridge-themes) at the application level?

**Comment by rupinderjeet** [comment] 2021-04-06 08:11
Hello @zsmb13 

I am not authorized to make changes in that section yet. I have discussed it with team a lot of times, and there's still some hope left that I may get assigned to work on it.

I believe this issue will be fixed with above added commit work. If not, I will add manifest declarations for my module.

If there's something wrong in handling the issue this way, please let me know.

**Comment by JcMinarro** [comment] 2021-04-08 15:20
Hi @rupinderjeet 
It has been fixed and we already released a [new versión](https://github.com/GetStream/stream-chat-android/releases/latest)
I'm closing this issue

**Closed by JcMinarro** 2021-04-08 15:20 UTC
Labels: next-release
