### ISSUE TITLE
Pdf preview doesn't work on MessageListView

### ISSUE THREAD

**Issue by Kravet** [GetStream/stream-chat-android#3003] opened 2022-01-31 10:28 UTC
**Describe the bug**
When user clicks on pdf file inside io.getstream.chat.android.ui.message.list.MessageListView, then "No preview available".

**SDK version**
//stream chat deps
    implementation "io.getstream:stream-chat-android-ui-components:4.27.0"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.4.0"
    implementation "io.coil-kt:coil:1.4.0"
    implementation 'androidx.activity:activity-ktx:1.4.0'

**To Reproduce**
1. Go to list of message inside MessageListView.
2. Upload pdf file.
3. Click on the pdf file.
4. See "No preview available" screen.

**Expected behavior**
See pdf file content preview.

**Device:**
 -Android emulator api 31
 - OnePlus 5t (android 10.0.1), 
 - OnePlus 6t.

**Screenshots**
"No preview available" screen
![image](https://user-images.githubusercontent.com/7354769/151777378-d1445722-203a-4f0b-bd76-69f7863feca2.png)

Chat with pdf where user clicks to open pdf preview
![image](https://user-images.githubusercontent.com/7354769/151777457-615b4705-9dfc-44fc-8393-fb82a2080ac1.png)

I use this code to present the list of message, where I click to the PDF file in the chat.
```
<io.getstream.chat.android.ui.message.list.MessageListView
        android:id="@+id/messageListView"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:clipToPadding="false"
        android:paddingBottom="16dp"
        app:layout_constraintBottom_toTopOf="@+id/messageInputView"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/headerDividerView" />
```

**Comment by filbabic** [comment] 2022-01-31 15:24
Hey @Kravet Thanks for reaching out!

I've just tested with a blank PDF file and opening it seems to work.

Can you give me a bit more information where the issue is happening:
- Which device is failing to open the file
- Does your device have a browser installer, or Google Drive app (as we're using that to open the document)
- Does this happen every single time
- Could you attach the file here so that we can try to reproduce it with that file (might be something with URL formatting when the file name isn't using latin letters (as you're using cyrillic in this example)).

Sorry for the late reply - I'll work on this to get a clear picture and a fix ASAP!

**Comment by Kravet** [comment] 2022-02-01 11:16
Yes, indeed, the problem is with Cyrillic in the file name. When I renamed to Latin, the preview worked.
Can you fix that on get-stream side, so pdf files with cyrillic names could be previewed inside io.getstream.chat.android.ui.message.list.MessageListView?

**Comment by filbabic** [comment] 2022-02-01 11:58
@Kravet Hey!

Yeah we're working on it - however, I managed to preview [МЕНЮ_РЕСТОРАНА.pdf](https://github.com/GetStream/stream-chat-android/files/7978204/_.pdf) yesterday when I tested it and it worked fine.

Do you mind sharing the following info with me:
- Can you upload the PDF here so I can test with it?
- Can you tell me which device you had this issue on (which Android version, which vendor etc.)?

**Comment by filbabic** [comment] 2022-02-03 10:49
@Kravet we've merged a fix around the encoding in #3017 so let me know if this works for you. You can use a SNAPSHOT build too to check this behavior.

Otherwise, we'd need your PDF file to see if it works, but with my tests (with the cyrillic alphabet named files) it worked fine!

**Comment by Kravet** [comment] 2022-02-03 15:13
Thanks! By the way I can't reproduce it anymore on 4.27.0.

It looks like it's something wrong with the specific file in the history. I can't neither preview it nor download.
But when I uploaded the very same file again later, then both preview and download works the new file.
So maybe the problem is not related to the Cyrillic at all, but this file is too old or just unavailable on server.

Checkout the video. It looks like the file is corrupted or unavailable on the server but it still look ok in the chat.

[https://drive.google.com/file/d/1uV28-CqI0qvB3JvTHYp71dxwBGRbt06Y/view?usp=sharing](url)

**Comment by filbabic** [comment] 2022-02-03 15:19
Hey @Kravet!

Thanks for the input! It might be that the upload went wrong for some reason and the file is broken. 

I'll close this issue for now and in case it appears again in the future, let us know and we can look into it again!

**Closed by filbabic** 2022-02-03 15:19 UTC
Labels: bug
