### ISSUE TITLE
Camera crashes the app

### ISSUE THREAD

**Issue by CrispBull** [GetStream/stream-chat-android#925] opened 2020-11-30 15:34 UTC
**Describe the bug**
On clicking the camera attachment icon in the messageInputView, the app crashes

**SDK version**
- 4.4.5

**To Reproduce**
Just running the app and clicking the icon, it crashes the app with no log shown. Ironically the sample app doesn't do this. What could I be doing wrong?

```kotlin
class StreamChatDetailFragment: Fragment() {


        override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
              super.onViewCreated(view, savedInstanceState)
              channelMessagesViewModel.bindView(chatDetailBinding.messageList, viewLifecycleOwner)
              messageInputViewModel.bindView(chatDetailBinding.messageInput, viewLifecycleOwner)
    }
}

```

I don't know what else I need to do

**Expected behavior**
On selecting the camera icon in the message input view and granting permission, I should be able to se the camera launched

**Device:**
 - Google Pixel 3 XL
 - Android version: 10

**Comment by zsmb13** [comment] 2020-12-01 13:20
The part where the crash produces no logs seems like a very odd problem, perhaps an issue with the specific device or logcat somehow. Can't see any reason why this would happen.

It would be really useful if you could provide a crash log or a minimal example project that reproduces the issue. The code provided so far seems fine on its own.

---

Just to further confirm, you're tapping the "Upload from a camera" option here, and that's what causes the crash?

![image](https://user-images.githubusercontent.com/12054216/100745656-e6edcd80-33df-11eb-8a86-186b1e189df9.png)

It also sounds like you've already granted permission, so you were prompted for permissions when you first tapped that button, granted them, and then the crash occurred?

**Comment by zsmb13** [comment] 2020-12-02 09:31
For the "no logs" issue: please make sure that you're not filtering the logs in any way. You should have no search input for Logcat, and "No Filters" set, like so:

![image](https://user-images.githubusercontent.com/12054216/100854549-6f747880-3489-11eb-9087-c9995fe53210.png)

**Comment by zsmb13** [comment] 2020-12-03 07:50
Any news on this, @CrispBull?

**Comment by CrispBull** [comment] 2020-12-03 19:03
@zsmb13 I have tried doing this and still get the same state of nothing being logged.

**Comment by zsmb13** [comment] 2020-12-04 09:04
We'll ship some fixes for FileProviders in the next release, which will be out later today, hopefully that will fix your issues with the camera.

In the meantime, if you could provide a minimal sample project that reproduces the problem you're having, we could look into it further, to verify the cause.

**Comment by JcMinarro** [comment] 2020-12-05 12:01
Hello @CrispBull 

New version has been released, could you check if this one fixes your issue?
The new version is 4.4.6
If this one is not fixing your issue, could you provide a sample project to reproduce your issue?

Thanks

**Comment by CrispBull** [comment] 2021-01-04 15:20
Hello @JcMinarro 

Sorry for the late response. I'm still having this issue. I'm getting the following error
```
 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myapp, PID: 857
    java.lang.IllegalArgumentException: Can only use lower 16 bits for requestCode
        at androidx.fragment.app.FragmentActivity.checkForValidRequestCode(FragmentActivity.java:714)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:672)
        at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234)
        at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:215)
        at androidx.activity.result.ActivityResultRegistry$4.launch(ActivityResultRegistry.java:211)
        at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:42)
        at com.getstream.sdk.chat.view.messageinput.MessageInputView$configAttachmentUI$4.onClick(MessageInputView.kt:247)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by zsmb13** [comment] 2021-01-04 15:33
This seems like a bug in the AndroidX Activity result APIs. Could you please try including this dependency in your project manually, and see if it fixes the issue? We'll also add this to the next release of the SDK.

```
implementation "androidx.fragment:fragment-ktx:1.3.0-rc01"
````

**Comment by CrispBull** [comment] 2021-01-04 17:44
That fixed it, thanks @zsmb13

**Comment by zsmb13** [comment] 2021-01-04 18:37
Awesome, closing this again then.

**Closed by zsmb13** 2021-01-04 18:37 UTC
Labels: bug
