### ISSUE TITLE
queryChannelsAsState sometimes emits messages in reversed order

### ISSUE THREAD

**Issue by cvb941** [GetStream/stream-chat-android#4605] opened 2022-12-23 13:12 UTC
**Describe the bug**
Using the offline queryChannelsAsState flow to load channels, the emitted channel's messages are ordered by their dates sometimes in ascending and sometimes in descending order.

It seems like the messages are cached in an order reversed from the order coming from the backend. 

**SDK version**
- 5.11.9

**To Reproduce**
Turn on offline caching, create a QueryChannelsRequest, use queryChannelsAsState. Observe the order of messages in the received channels. The first message will sometimes be the latest and sometimes the oldest.

**Expected behavior**
We can just sort the messages by ourselves for now. To prevent any problems though, it would be nice to have a consistent message ordering from queryChannelsAsState.

**Comment by MarinTolic** [comment] 2023-01-05 11:17
Hi @cvb941,

Out attempts at reproducing this behavior in our sample apps have been unsuccessful.

If you are able to share a sample displaying the behavior or reproduce the behavior in one of our sample apps, that would be helpful in addressing the issue.

Kind regards,
Marin.

**Comment by MarinTolic** [comment] 2023-01-05 11:20
Also, sharing your `QueryChannelsRequest` along with the values used to create it might help as well.

Kind regards,
Marin.

**Comment by filbabic** [comment] 2023-02-07 08:18
Closing due to lack of comms.

**Closed by filbabic** 2023-02-07 08:18 UTC
Labels: bug
