### ISSUE TITLE
Problems with DNS resolution (chat.stream-io-api.com)

### ISSUE THREAD

**Issue by workspace** [GetStream/stream-chat-android#2443] opened 2021-10-06 05:22 UTC
**Describe the bug**
### some related logs
- [Events] onFailure: java.net.UnknownHostException: Unable to resolve host "chat.stream-io-api.com": No address associated with hostname
- [SocketService] Status code: -1, with stream code: 1003, description: See stack trace in logs. Intercept error in error handler of setUser
- [Events] onFailure: javax.net.ssl.SSLException: Read error: ssl=0x7011e26288: I/O error during system call, Software caused connection abort
- [Events] onFailure: javax.net.ssl.SSLException: Read error: ssl=0x7ae273aec8: I/O error during system call, Software caused connection abort
- [Events] onFailure: java.net.SocketException: Software caused connection abort

### exception
```
java.net.UnknownHostException: Unable to resolve host "chat.stream-io-api.com": No address associated with hostname
       at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
       at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
       at java.net.InetAddress.getAllByName(InetAddress.java:1152)
       at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.java:49)
       at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:164)
       at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:129)
       at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:71)
       at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:205)
       at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:106)
       at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:74)
       at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.java:255)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:32)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:95)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:83)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:76)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.java:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
Caused by android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
       at libcore.io.Linux.android_getaddrinfo(Linux.java)
       at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
       at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:200)
       at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:74)
       at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
       at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
       at java.net.InetAddress.getAllByName(InetAddress.java:1152)
       at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.java:49)
       at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:164)
       at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:129)
       at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:71)
       at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:205)
       at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:106)
       at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:74)
       at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.java:255)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:32)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:95)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:83)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:76)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.java:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

**SDK version**
- 4.18.0

**To Reproduce**
It is hard to reproduce.

**Expected behavior**
Able to resolve host "chat.stream-io-api.com"

**Device:**
 Almost samsung devices.
![image](https://user-images.githubusercontent.com/7759511/136144439-9501f63a-384d-4f89-9fb5-b0a5027fb668.png)

**Screenshots**
### os
![image](https://user-images.githubusercontent.com/7759511/136144878-66baf76f-37cd-4b0c-8e57-f358fb659bed.png)

### device state
![image](https://user-images.githubusercontent.com/7759511/136144850-8beb55ca-0b9e-41b3-8d38-4ca12fee7e74.png)

**Comment by workspace** [comment] 2021-10-06 08:01
We also think it is temporary DNS issue from some isp, however, more than 5 ISP founded from users with dns issue.

In okhttp github, there is an issue which is similar to this problem.
https://github.com/square/okhttp/issues/3919

**Comment by zsmb13** [comment] 2021-10-07 11:49
I'm going to close this for now, as the issue is likely not on our end. We'll keep monitoring the situation on our end. Feel free to re-open the issue if you see problems again.

**Closed by zsmb13** 2021-10-07 11:49 UTC
Labels: bug
