### ISSUE TITLE
Inconsistent and incorrect channel unread count

### ISSUE THREAD

**Issue by bibibilu** [GetStream/stream-chat-android#1347] opened 2021-02-06 01:27 UTC
#1226 Hi! The issue seems still exist in 4.5.3.
The total unread count at the bottom is correct, and it can be seen from the video that sum of channel unread count is inconsistent and not equal to the total count (not always happen, can be from time to time reproduced by refresh / reopen the app/ receiving new message)

https://user-images.githubusercontent.com/55115952/107104617-506ecb80-67d7-11eb-9999-62bfae9cac2e.mp4

**Comment by JcMinarro** [comment] 2021-02-08 11:23
Hello @bibibilu 
Could you share the code you use to render the unread badge?

**Comment by bibibilu** [comment] 2021-02-09 08:35
Code for total unread badge:
```
ChatDomain.instance().totalUnreadCount.observe(viewLifecycleOwner, Observer {
        badge.isVisible = it > 0
        badge.number = it
      })
```
Code for channel unread badge is exactly the way as being bold in #1226 - my ChannelsView is bound to ChannelsViewModel, using a custom ChannelViewHolderFactory and override bind function for ChannelListItemViewHolder as follow:
```
@Override
public void bind(@NotNull Channel channel, int i, @NotNull ChannelItemPayloadDiff channelItemPayloadDiff) {
    super.bind(channel, i, channelItemPayloadDiff);
    TextView count = view.findViewById(R.id.channelUnreadCountTextView);
    unreadBadge.setVisibility(channel.getUnreadCount() == 0 ? View.GONE : View.VISIBLE);
    count.setText(String.valueOf(channel.getUnreadCount()));
}
```

**Comment by samiuelson** [comment] 2021-04-23 08:45
Hi @bibibilu,
recently we've added improvements to the unread count code. Could you check out the latest SDK version 4.9.0 and verify the issue is fixed?

**Comment by bychkovdmitry** [comment] 2021-05-03 16:32
Hello @bibibilu 
This PR is also relevant to this issue: [#1833](https://github.com/GetStream/stream-chat-android/pull/1833). The code will be merged soon and shipped with the next release.

**Comment by JcMinarro** [comment] 2021-05-13 08:12
Hello @bibibilu 

A [new version](https://github.com/GetStream/stream-chat-android/releases/latest) has been released that fix it

**Closed by JcMinarro** 2021-05-13 08:12 UTC
Labels: bug, next-release
