### ISSUE TITLE
Unable to create chat with a deleted user

### ISSUE THREAD

**Issue by bibinkrishnan** [GetStream/stream-chat-android#3048] opened 2022-02-07 11:03 UTC
Can't able to create chat with a deleted user in the history
**SDK version**
- 4.21.0

**To Reproduce**
1. Go to Chat list
2. Delete any existing user from the chat list
3. Try to create a new "Messaging" chat with the same user

_**Status code: 403, with stream code: 17, description: GetOrCreateChannel failed with error: "User 'XXX' with role channel_member is not allowed to access Resource RecreateChannel on channel type messaging"**_

**Comment by filbabic** [comment] 2022-02-07 16:27
Closing as this is a duplicate of: https://github.com/GetStream/stream-chat-android/issues/3042

**Closed by filbabic** 2022-02-07 16:27 UTC
Labels: bug
